"""
A simple visualizer for the heat equation simulation output.

This script uses the ParaView Python API to create a simple visualization pipeline from the .vti files generated by the heat equation simulation. It allows you to
quickly inspect the results without manually opening ParaView and setting up the pipeline. You can also save a screenshot of the visualization.
To use this visualizer, run it in an environment where ParaView's Python modules are available (e.g., using pvpython). It will prompt you to select which .vti file to visualize and then display the results in a render window.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

import numpy as np
from pyevtk.hl import imageToVTK

class ParaViewSeriesVisualizer:
    """Builds a ParaView simple pipeline from a .vti file series."""

    def __init__(self, series_first_file: Path):
        self.series_first_file = series_first_file
        self.series_files = self._discover_series_files(series_first_file)
        self._simple = self._import_paraview_simple()

    @staticmethod
    def _discover_series_files(series_first_file: Path) -> list[Path]:
        stem = series_first_file.stem
        if "_" not in stem:
            return [series_first_file]

        prefix, suffix = stem.rsplit("_", 1)
        if not suffix.isdigit():
            return [series_first_file]

        candidates = sorted(series_first_file.parent.glob(f"{prefix}_*.vti"))
        if not candidates:
            return [series_first_file]
        return candidates

    @staticmethod
    def _import_paraview_simple():
        try:
            import paraview.simple as pvs
        except Exception as exc:  # pragma: no cover - depends on external installation
            raise RuntimeError(
                "paraview.simple is unavailable. Run this script with pvpython "
                "or in a Python environment where ParaView modules are installed."
            ) from exc
        return pvs

    def show(
        self,
        use_glyphs: bool = False,
        save_screenshot_path: Optional[Path] = None,
        keep_window_open: bool = False,
    ) -> None:
        pvs = self._simple

        # Reset state for repeatable scripts.
        pvs.Disconnect()
        pvs.Connect()

        reader = pvs.XMLImageDataReader(FileName=[str(path) for path in self.series_files])
        reader.PointArrayStatus = ["temperature", "heat_flux"]
        pvs.UpdatePipeline(proxy=reader)

        render_view = pvs.GetActiveViewOrCreate("RenderView")
        display = pvs.Show(reader, render_view)

        display.Representation = "Surface"
        pvs.ColorBy(display, ("POINTS", "temperature"))
        display.RescaleTransferFunctionToDataRange(True, False)

        temp_lut = pvs.GetColorTransferFunction("temperature")
        temp_pwf = pvs.GetOpacityTransferFunction("temperature")
        temp_lut.ApplyPreset("Cool to Warm", True)
        temp_lut.RescaleTransferFunction(0.0, 1.2)
        temp_pwf.RescaleTransferFunction(0.0, 1.2)

        scalar_bar = pvs.GetScalarBar(temp_lut, render_view)
        scalar_bar.Title = "Temperature"
        scalar_bar.ComponentTitle = ""
        display.SetScalarBarVisibility(render_view, True)

        if use_glyphs:
            glyph = pvs.Glyph(Input=reader, GlyphType="Line")
            glyph.OrientationArray = ["POINTS", "heat_flux"]
            glyph.ScaleArray = ["POINTS", "heat_flux"]
            glyph.ScaleFactor = 0.003
            glyph.GlyphMode = "Uniform Spatial Distribution (Bounds Based)"
            if hasattr(glyph, "MaximumNumberOfSamplePoints"):
                glyph.MaximumNumberOfSamplePoints = 5000
            if hasattr(glyph, "Seed"):
                glyph.Seed = 7

            glyph_display = pvs.Show(glyph, render_view)
            pvs.ColorBy(glyph_display, None)
            glyph_display.SetScalarBarVisibility(render_view, False)
            glyph_display.DiffuseColor = [1.0, 1.0, 1.0]
            glyph_display.AmbientColor = [1.0, 1.0, 1.0]

        render_view.ResetCamera()
        render_view.ViewSize = [1280, 720]
        pvs.Render()

        if save_screenshot_path is not None:
            pvs.SaveScreenshot(str(save_screenshot_path), render_view, ImageResolution=[1920, 1080])
            print(f"Saved screenshot: {save_screenshot_path}")

        if keep_window_open:
            print("Entering interactive mode. Close the render window to finish.")
            pvs.Interact()


if __name__ == "__main__":

    output_dir = Path("output")
    files = sorted(output_dir.glob("heat_*.vti"))

    try:
        heat_file_idx = int(input(f"Enter heat file index to visualize (0-{len(files)-1}): "))
    except ValueError:
        print("Invalid input. Defaulting to index 0.")
        heat_file_idx = 0

    try:
        viz = ParaViewSeriesVisualizer(files[heat_file_idx])
    except RuntimeError as err:
        print()
        print(err)
        print("Simulation data is ready. Open output/heat_0000.vti in ParaView to inspect manually.")
    else:
        KEEP_WINDOW_OPEN = True
        viz.show(
            use_glyphs=True,
            save_screenshot_path=Path("output") / "heat_preview.png",
            keep_window_open=KEEP_WINDOW_OPEN,
        )
